swagger: '2.0'
info:
  version: '1.0.0'
  title: Gamification
  description: An API to implement gamification features in the swagger-2.0 specification. 
  
    Done 
      - /bagges
    
    ToDo 
      - /levels
      (- /rules)
      (- /users)
      (- /leaderboards)
    
  contact:
    name: Guillaume Serneels
    email: guillaume.serneels@heig-vd.ch
    url: www.heig-vd.ch
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /badges:
    get:
      summary: Returns every badges
      description: |
        Returns every badges
      operationId: findBadges
      responses:
        '200':
          description: badges response
          schema:
            type: array
            items:
              $ref: '#/definitions/badge'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      summary: Creates a new badge
      description: |
        Creates a new badge
      operationId: addBadge
      parameters:
        - name: badge
          in: body
          description: Badge object to add to the store
          required: true
          schema:
            $ref: '#/definitions/badge'
      responses:
        '200':
          description: badge response
          schema:
            $ref: '#/definitions/badge'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
   
  /badges/{badgeId}:   
    get:
      summary: Returns a single badge
      description: |
        Returns a single badge
      operationId: findBadge
      parameters:
        - name: badgeId
          in: path
          description: ID of badge to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: badge response
          schema:
            $ref: '#/definitions/badge'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    put:
      summary: Update an existing badge
      description: |
        Update an existing badge
      operationId: UpdateBadge
      parameters:
        - name: badge
          in: body
          description: Badge object to add to the store
          required: true
          schema:
            $ref: '#/definitions/badge'
        - name: badgeId
          in: path
          description: Id of the badge that needs to be updated
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: badge response
          schema:
            $ref: '#/definitions/badge'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      summary: Delete an existing badge
      description: |
        Delete an existing badge
      operationId: DeleteBadge
      parameters:
        - name: badgeId
          in: path
          description: Id of the badge that needs to be deleted
          required: true
          type: integer
          format: int64
      responses:
        '404':
          description: Badge not found
        '400':
          description: Invalid Id supplied
          
definitions:
  badge:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
